{
    'name': '[LOCVE] Venezuela: POS fiscal printer',
    'version': '18.0.1.9.17',
    'category': 'LocVe [Localization]',
    'summary': 'Fiscal printing using serial ports',
    'author': 'Remake Ing Nerdo Pulido',
    'company': 'José Luis Vizcaya López remake Ing Nerdo Pulido',
    'maintainer': 'José Luis Vizcaya López remake Ing Nerdo Pulido',
    'website': 'https://github.com/birkot',
    'description': 'Impresoras modelos SRP812, DT230, HKA80, PP9, PP9-PLUS, PD3100DL, TD1140.',
    'depends': ['point_of_sale', 'pos_igtf_tax', 'l10n_ve_binaural'],
    'data': [
        'security/ir.model.access.csv',
        'views/inherited_views.xml',
        'views/x_pos_fiscal_printer_views.xml',
        'views/pos_report_z.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'pos_fiscal_printer/static/src/scss/**/*',
            'pos_fiscal_printer/static/src/app/popup/nota_credito_popup.xml',
            'pos_fiscal_printer/static/src/app/popup/nota_credito_popup.js',
            'pos_fiscal_printer/static/src/app/popup/close_pos_popup_patch.xml',
            'pos_fiscal_printer/static/src/app/popup/close_pos_popup_patch.js',
            'pos_fiscal_printer/static/src/app/utils/data_helper.js',
            'pos_fiscal_printer/static/src/app/utils/printing_mixin.js',
            'pos_fiscal_printer/static/src/app/screens/receipt_screen/receipt_screen_patch.xml',
            'pos_fiscal_printer/static/src/app/screens/receipt_screen/receipt_screen_patch.js',
            'pos_fiscal_printer/static/lib/js/**/*',
            'pos_fiscal_printer/static/lib/css/**/*',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
}
